version: '3'
services:
  db:
    image: postgres:14.3-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: machinery_complex
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
  app:
    image: egorkokhan/machineryback:v11-prod
    container_name: application
    ports:
      - "8080:8080"
    restart: "no"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/machinery_complex
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - db
  nginx:
    image: nginx:1.17.2-alpine
    container_name: nginx
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "8989:8989"
