spring:
  profiles:
    active: dev

server:
  error:
    include-message: always

---

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/machinery_complex}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update


---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

