spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/machinery_complex
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

