spring:
  profiles:
    active: prod

server:
  error:
    include-message: always

gams:
  path: C:\GAMS\39\apifiles\Java\api

jwt:
  expiration:
    access:
      minutes: 5
    refresh:
      minutes: 30
  secret:
    access: supermegasecret
    refresh: supermegarefreshsecret
---

spring:
  profiles: prod
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/machinery_complex}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:root}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: dev
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update


---

spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:testdb
    username: postgres
    password: root
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
    - org.springframework.boot.actuate.autoconfigure.security.servlet.ManagementWebSecurityAutoConfiguration

